'use client';

import Link from 'next/link';
import type { LucideIcon } from 'lucide-react';
import { ArrowLeft, BookOpen, ChevronRight, Download, Edit3, FileText, MoreHorizontal, Plus, Search, Trash2, UserRound, UsersRound } from 'lucide-react';

export type SchoolView = 'students' | 'student-detail' | 'courses' | 'course-detail' | 'teachers' | 'schedule' | 'settings';

const students = [['Rasolonjatoavo Tiana', 'Informatique', 'L1', 'tiana.raso@get.mg', '034 12 345 67', 'Actif'], ['Rakotoarivelo Miora', 'Génie Civil', 'L1', 'miora.rakoto@get.mg', '034 56 789 01', 'Actif'], ['Andriamiadana Fanja', 'Management', 'L2', 'fanja.andria@get.mg', '033 45 678 90', 'En attente'], ['Rabeharisoa Lova', 'Informatique', 'L1', 'lova.rabe@get.mg', '034 56 789 01', 'Actif'], ['Rakotomalala Jery', 'Électrotechnique', 'L1', 'jery.rakoto@get.mg', '032 12 345 67', 'Actif'], ['Razafindrakoto Haja', 'Génie Civil', 'L2', 'haja.raza@get.mg', '033 77 889 23', 'Actif']];
const courses = [['Algorithmique Avancée', 'Informatique', 'L1', 'Dr. Rakotomalala L.', '4'], ['Structures de Données', 'Informatique', 'L1', 'M. Andriamihaja R.', '4'], ['Mathématiques Générales', 'Génie Civil', 'L1', 'Dr. Rasoavelo H.', '4'], ['Mécanique du Sol', 'Génie Civil', 'L2', 'Dr. Randrianarison P.', '6'], ['Comptabilité Générale', 'Management', 'L1', 'Mme. Raharisoa T.', '4'], ['Électrotechnique Générale', 'Électrotechnique', 'L1', 'Dr. Raharimalala T.', '4']];
const teachers = [['Dr. Rakotomalala L.', 'Informatique', 'Algorithmique', 'rakotomalala.l@get.mg'], ['M. Andriamihaja R.', 'Informatique', 'Structures de Données', 'andriamihaja.r@get.mg'], ['Mme. Rasoavelo H.', 'Génie Civil', 'Mathématiques', 'rasoavelo.h@get.mg'], ['Dr. Randrianarison P.', 'Génie Civil', 'Mécanique', 'randrianarison.p@get.mg'], ['Mme. Raharisoa T.', 'Management', 'Comptabilité', 'raharisoa.t@get.mg'], ['Dr. Raharimalala T.', 'Électrotechnique', 'Électrotechnique', 'raharimalala.t@get.mg']];

export function SchoolManagementView({ view }: { view: SchoolView }) {
  if (view === 'student-detail') return <StudentDetail />;
  if (view === 'course-detail') return <CourseDetail />;
  if (view === 'schedule') return <Schedule />;
  if (view === 'settings') return <SettingsView />;
  const config = view === 'students' ? { title: 'Étudiants', subtitle: 'Gérez et consultez la liste des étudiants.', action: 'Ajouter un étudiant', icon: UsersRound } : view === 'courses' ? { title: 'Cours', subtitle: 'Gérez les cours et modules de votre établissement.', action: 'Ajouter un cours', icon: BookOpen } : { title: 'Professeurs', subtitle: 'Gérez et consultez leurs informations.', action: 'Ajouter un professeur', icon: UserRound };
  return <PageShell {...config}><Directory type={view} /></PageShell>;
}

function PageShell({ title, subtitle, action, children }: { title: string; subtitle: string; action?: string; children: React.ReactNode }) { return <div className="mx-auto max-w-[1500px]"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-extrabold tracking-tight text-[#111949]">{title}</h1><p className="mt-1 text-sm text-violet-600">{subtitle}</p></div>{action && <button className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-violet-700 to-indigo-500 px-4 py-2.5 text-xs font-bold text-white shadow-md shadow-violet-200"><Plus className="size-4" />{action}</button>}</header>{children}</div>; }
function Directory({ type }: { type: 'students' | 'courses' | 'teachers' }) { const isStudents = type === 'students'; const rows = isStudents ? students : type === 'courses' ? courses : teachers; const headers = isStudents ? ['Étudiant', 'Filière', 'Niveau', 'Email', 'Téléphone', 'Statut', 'Actions'] : type === 'courses' ? ['Cours', 'Filière', 'Niveau', 'Professeur', 'Crédits', 'Actions'] : ['Professeur', 'Filière', 'Spécialité', 'Email', 'Statut', 'Actions']; return <section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><div className="mb-6 flex flex-wrap gap-3"><div className="relative min-w-[240px] flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input className="h-10 w-full rounded-lg border border-slate-200 pl-10 pr-3 text-xs outline-none focus:border-violet-500" placeholder={`Rechercher un${isStudents ? ' étudiant' : type === 'courses' ? ' cours' : ' professeur'}...`} /></div>{['Filière', 'Niveau', 'Statut'].slice(0, isStudents ? 3 : 2).map((label) => <button key={label} className="h-10 min-w-28 rounded-lg border border-slate-200 px-3 text-left text-xs text-slate-500">{label}<span className="float-right">⌄</span></button>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-[11px]"><thead className="border-b border-slate-100 text-slate-400"><tr>{headers.map((header) => <th key={header} className="pb-3 font-semibold">{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-b border-slate-50 text-slate-600"><td className="py-3 font-bold text-[#28315e]">{row[0]}</td>{row.slice(1).map((cell, index) => <td key={`${row[0]}-${index}`}>{cell}</td>)}{type === 'teachers' && <td><Status value="Actif" /></td>} {isStudents && <td><Status value={row[5]} /></td>}<td><div className="flex gap-2 text-violet-600"><Link href={type === 'students' ? '/dashboard/school/students/rasolonjatoavo' : type === 'courses' ? '/dashboard/school/courses/algorithmique-avancee' : '#'}><Edit3 className="size-4" /></Link><MoreHorizontal className="size-4" /></div></td></tr>)}</tbody></table></div><div className="mt-6 flex items-center justify-between text-xs text-slate-500"><span>Affichage 1 à 6 sur {type === 'students' ? '2 456' : type === 'courses' ? '156' : '98'} {type === 'students' ? 'étudiants' : type === 'courses' ? 'cours' : 'professeurs'}</span><span className="flex items-center gap-3"><ChevronRight className="size-4 rotate-180" /><b className="grid size-6 place-items-center rounded bg-violet-600 text-white">1</b><span>2</span><span>3</span><ChevronRight className="size-4" /></span></div></section>; }
function StudentDetail() { return <PageShell title="Détail étudiant" subtitle="Informations et suivi académique"><Link href="/dashboard/school/students" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-slate-500"><ArrowLeft className="size-4" />Retour</Link><div className="grid gap-4 xl:grid-cols-[260px_1fr]"><aside className="rounded-xl border border-slate-100 bg-white p-5 text-center shadow-sm"><span className="mx-auto grid size-24 place-items-center rounded-full bg-violet-100 text-3xl font-black text-violet-600">RT</span><h2 className="mt-4 font-extrabold text-[#17204e]">Rasolonjatoavo Tiana</h2><p className="mt-1 text-xs text-violet-600">L1 · Informatique</p><Status value="Actif" /><p className="mt-4 text-[10px] text-slate-500">GET2024-ESPA-1024</p></aside><section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex gap-7 border-b border-slate-100 pb-3 text-xs font-bold text-violet-600"><span>Informations</span><span className="text-slate-500">Notes</span><span className="text-slate-500">Présences</span><span className="text-slate-500">Paiements</span><span className="text-slate-500">Documents</span></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_210px]"><InfoPanel title="Informations académiques" rows={[['Filière', 'Informatique'], ['Niveau', 'Licence 1'], ['Groupe', 'L1 – INFO – A'], ['Date d’inscription', '10 octobre 2024'], ['Statut', 'Actif']]} /><ActionPanel /></div><InfoPanel title="Informations personnelles" rows={[['Sexe', 'Féminin'], ['Nationalité', 'Malagasy'], ['Email', 'tiana.raso@get.mg'], ['Téléphone', '034 12 345 67'], ['Adresse', 'Antananarivo, Madagascar']]} /></section></div></PageShell>; }
function CourseDetail() { return <PageShell title="Détail cours" subtitle="Cours › Détail du cours"><Link href="/dashboard/school/courses" className="mb-5 inline-flex items-center gap-2 text-xs font-bold text-slate-500"><ArrowLeft className="size-4" />Retour</Link><div className="grid gap-4 xl:grid-cols-[1.1fr_1fr_220px]"><section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex gap-3"><span className="grid size-12 place-items-center rounded-xl bg-emerald-100 text-emerald-600"><BookOpen className="size-6" /></span><div><h2 className="font-extrabold text-[#17204e]">Algorithmique Avancée</h2><p className="mt-1 text-xs text-slate-500">Informatique · Licence 1</p><Status value="Actif" /></div></div></section><InfoPanel title="Informations générales" rows={[['Code du cours', 'INFO101'], ['Crédits', '4'], ['Heures / Semaine', '4h'], ['Semestre', 'Semestre 2'], ['Langue d’enseignement', 'Français']]} /><section className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm"><h3 className="font-bold text-[#17204e]">Actions</h3><div className="mt-3 space-y-2"><Action label="Modifier" icon={Edit3} /><Action label="Dupliquer" icon={FileText} /><Action label="Supprimer" icon={Trash2} danger /></div></section></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><InfoPanel title="Professeur" rows={[['Dr. Rakotomalala L.', 'rakotomalala.l@get.mg']]} /><InfoPanel title="Description" rows={[['', 'Ce cours introduit les concepts avancés de l’algorithmique et les techniques de conception.']]} /><InfoPanel title="Étudiants inscrits" rows={[['246 étudiants', 'Voir la liste']]} /></div></PageShell>; }
function Schedule() { const colors = ['bg-violet-100 text-violet-700', 'bg-emerald-100 text-emerald-700', 'bg-orange-100 text-orange-700', 'bg-blue-100 text-blue-700']; return <PageShell title="Emploi du temps" subtitle="Consultez et gérez les emplois du temps."><section className="rounded-xl border border-slate-100 bg-white p-5 shadow-sm"><div className="mb-5 flex flex-wrap justify-between gap-3"><div className="flex gap-3"><button className="rounded-lg border border-slate-200 px-3 py-2 text-xs">Filière : Informatique</button><button className="rounded-lg border border-slate-200 px-3 py-2 text-xs">Niveau : L1</button><button className="rounded-lg border border-slate-200 px-3 py-2 text-xs">Groupe : Tous</button></div><button className="rounded-lg bg-violet-600 px-4 py-2 text-xs font-bold text-white">Semaine</button></div><div className="grid grid-cols-[70px_repeat(6,1fr)] border-l border-t border-slate-100 text-center text-[10px]"><div className="border-b border-r border-slate-100 p-3" />{['Lundi 12', 'Mardi 13', 'Mercredi 14', 'Jeudi 15', 'Vendredi 16', 'Samedi 17'].map((day) => <div key={day} className="border-b border-r border-slate-100 p-3 font-bold text-slate-500">{day}</div>)}{['08:00', '10:00', '12:00', '14:00', '16:00'].map((time, row) => <><div key={time} className="border-b border-r border-slate-100 p-4 text-slate-400">{time}</div>{Array.from({ length: 6 }).map((_, column) => <div key={`${time}-${column}`} className="min-h-20 border-b border-r border-slate-100 p-1">{(row + column) % 3 === 0 && <div className={`rounded p-2 text-left font-semibold ${colors[(row + column) % colors.length]}`}>{['Algorithmique Avancée', 'Structures de Données', 'Mathématiques Générales', 'Anglais Technique'][row % 4]}<small className="mt-1 block font-normal">Salle B204</small></div>}</div>)}</>)}</div></section></PageShell>; }
function SettingsView() { return <PageShell title="Paramètres" subtitle="Gérez les paramètres de votre établissement."><section className="rounded-xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex gap-7 border-b border-slate-100 pb-4 text-xs font-bold"><span className="text-violet-600">Informations établissement</span><span className="text-slate-500">Année académique</span><span className="text-slate-500">Utilisateurs</span><span className="text-slate-500">Notifications</span><span className="text-slate-500">Sécurité</span></div><div className="mt-6 grid gap-6 lg:grid-cols-[1fr_280px]"><div><h2 className="font-bold text-[#17204e]">Informations établissement</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><SettingField label="Nom de l’établissement" value="École Supérieure Polytechnique d’Antananarivo (ESPA)" wide /><SettingField label="Email" value="contact@espa.mg" /><SettingField label="Téléphone" value="+261 34 12 345 67" /><SettingField label="Adresse" value="Lot II 4B, Ambonihitsiroa, Antananarivo, Madagascar" wide /></div></div><aside className="rounded-xl bg-violet-50 p-5"><h3 className="font-bold text-[#17204e]">À propos</h3><div className="mt-4 space-y-3 text-xs text-slate-600"><p><b className="block text-slate-400">ID établissement</b>GET-ESPA-001</p><p><b className="block text-slate-400">Date de création</b>15 janvier 2010</p><p><b className="block text-slate-400">Nombre d’étudiants</b>2 456</p><p><b className="block text-slate-400">Nombre de professeurs</b>98</p></div></aside></div><div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-5"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-full bg-violet-100 font-black text-violet-600">E</span><div><p className="text-xs font-bold">Logo de l’établissement</p><p className="text-[10px] text-slate-500">PNG, JPG ou WEBP, 5 Mo max</p></div></div><button className="rounded-lg bg-violet-600 px-4 py-2 text-xs font-bold text-white">Enregistrer les modifications</button></div></section></PageShell>; }
function InfoPanel({ title, rows }: { title: string; rows: string[][] }) { return <section className="mt-4 rounded-xl border border-slate-100 p-4"><h3 className="text-xs font-extrabold text-violet-600">{title}</h3><dl className="mt-3 divide-y divide-slate-100">{rows.map(([key, value]) => <div key={`${key}-${value}`} className="grid grid-cols-2 gap-3 py-2 text-xs"><dt className="text-slate-400">{key}</dt><dd className="font-semibold text-[#34406b]">{value}</dd></div>)}</dl></section>; }
function ActionPanel() { return <section className="rounded-xl border border-slate-100 p-4"><h3 className="text-xs font-extrabold text-violet-600">Actions</h3><div className="mt-3 space-y-2"><Action label="Modifier" icon={Edit3} /><Action label="Voir le dossier" icon={FileText} /><Action label="Imprimer la fiche" icon={Download} /><Action label="Désactiver le compte" icon={Trash2} danger /></div></section>; }
function Action({ label, icon: Icon, danger = false }: { label: string; icon: LucideIcon; danger?: boolean }) { return <button className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-xs font-semibold ${danger ? 'bg-rose-50 text-rose-600' : 'bg-violet-50 text-violet-600'}`}><Icon className="size-4" />{label}</button>; }
function SettingField({ label, value, wide = false }: { label: string; value: string; wide?: boolean }) { return <label className={wide ? 'sm:col-span-2' : ''}><span className="mb-1.5 block text-xs font-bold text-[#34406b]">{label}</span><input defaultValue={value} className="h-10 w-full rounded-lg border border-slate-200 px-3 text-xs outline-none focus:border-violet-500" /></label>; }
function Status({ value }: { value: string }) { return <span className={`inline-block rounded px-2 py-1 text-[10px] font-bold ${value === 'Actif' || value === 'Validée' ? 'bg-emerald-50 text-emerald-600' : 'bg-orange-50 text-orange-500'}`}>{value}</span>; }
