import type { ReactNode } from 'react';
import Link from 'next/link';
import { Bell, BookOpen, CheckCircle2, ChevronRight, Download, FileText, WalletCards } from 'lucide-react';

type View = 'parcours' | 'courses' | 'schedule' | 'grades' | 'documents' | 'messages' | 'settings' | 'news' | 'opportunities' | 'library';

const courseRows = [
  ['Algorithmique Avancée', 'Pr. A. Andrianarison', '15,5/20', '75%'],
  ['Bases de Données', 'Pr. T. Ravelomanana', '14/20', '70%'],
  ['Anglais Technique', 'Dr. L. Rakotomalala', '16/20', '80%'],
  ['Mathématiques Discrètes', 'Pr. H. Randrianarisoa', '12/20', '60%'],
];

export function StudentPortalView({ view }: { view: View }) {
  const titles: Record<View, string> = { parcours: 'Mon parcours', courses: 'Mes cours', schedule: 'Emploi du temps', grades: 'Mes notes', documents: 'Mes documents', messages: 'Messages', settings: 'Paramètres', news: 'Actualités', opportunities: 'Stages & emplois', library: 'Bibliothèque' };
  return <div className="mx-auto max-w-[1180px] text-[#111a4b]"><header className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-extrabold">{titles[view]}</h1><p className="mt-1 text-xs text-slate-500">Espace étudiant · ESPA – 2ᵉ année Informatique</p></div><button className="relative rounded-lg p-2 text-slate-500 hover:bg-violet-50"><Bell className="size-5" /><span className="absolute right-1 top-1 size-2 rounded-full bg-rose-500" /></button></header>{renderView(view)}</div>;
}

function renderView(view: View) {
  if (view === 'parcours') return <Parcours />;
  if (view === 'courses') return <Courses />;
  if (view === 'schedule') return <Schedule />;
  if (view === 'grades') return <Grades />;
  if (view === 'documents') return <Documents />;
  if (view === 'messages') return <Messages />;
  if (view === 'settings') return <SettingsView />;
  return <ComingSoon title={view === 'news' ? 'Actualités de l’établissement' : view === 'opportunities' ? 'Stages & emplois' : 'Bibliothèque en ligne'} icon={view === 'news' ? Bell : view === 'opportunities' ? WalletCards : BookOpen} />;
}

function Parcours() {
  const subjects = [['Algorithmique', '6/6', 'Validé'], ['Bases de Données', '4/6', 'En cours'], ['Réseaux & Télécoms', '2/6', 'En cours'], ['Mathématiques', '6/6', 'Validé'], ['Anglais', '0/6', 'Non commencé'], ['Management', '0/6', 'Non commencé']];
  return <div className="grid gap-4 lg:grid-cols-3"><Panel className="lg:col-span-2" title="Progression du programme"><div className="mt-5 flex items-center gap-7 rounded-xl bg-violet-50/70 p-5"><div className="flex size-28 shrink-0 items-center justify-center rounded-full border-[10px] border-violet-200 border-t-violet-600"><div className="text-center"><p className="text-2xl font-extrabold text-violet-600">60%</p><p className="text-[10px] text-slate-500">Complété</p></div></div><div className="grid flex-1 grid-cols-2 gap-4 text-xs"><Info label="Crédits validés" value="18/30" /><Info label="Matières validées" value="12/20" /><Info label="Semestre actuel" value="S2 – 2024/2025" /></div></div></Panel><Panel title="Informations"><div className="mt-3 space-y-3 text-xs"><Info label="Filière" value="Informatique" /><Info label="Niveau" value="2ᵉ année" /><Info label="Admission" value="2023" /><Info label="Statut" value="Régulier" /></div></Panel><Panel className="lg:col-span-2" title="Matières du programme"><div className="mt-3 divide-y divide-slate-100">{subjects.map(([subject, credits, state]) => <div key={subject} className="flex items-center gap-3 py-2.5 text-xs"><CheckCircle2 className={`size-4 ${state === 'Validé' ? 'text-emerald-500' : 'text-slate-300'}`} /><span className="flex-1 font-semibold">{subject}</span><span className="text-slate-500">{credits}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${state === 'Validé' ? 'bg-emerald-50 text-emerald-600' : state === 'En cours' ? 'bg-blue-50 text-blue-600' : 'bg-rose-50 text-rose-500'}`}>{state}</span></div>)}</div></Panel><Panel title="Prochains jalons"><div className="mt-3 space-y-5 border-l-2 border-violet-200 pl-4 text-xs"><Timeline label="Fin du semestre S2" date="30 juin 2025" /><Timeline label="Examens finaux" date="01 – 12 juillet 2025" /><Timeline label="Publication résultats" date="20 juillet 2025" /><Timeline label="Début S3" date="01 septembre 2025" /></div><button className="mt-5 w-full rounded-lg bg-violet-600 py-2 text-xs font-bold text-white">Télécharger mon relevé</button></Panel></div>;
}

function Courses() { return <Panel title="Mes cours" action="Voir d’ensemble"><div className="mt-4 space-y-3">{courseRows.map(([title, teacher, grade, progress]) => <div key={title} className="rounded-xl border border-slate-100 p-4"><div className="flex items-start justify-between"><div><p className="text-xs font-extrabold">{title}</p><p className="mt-1 text-[11px] text-slate-500">{teacher}</p></div><span className="text-sm font-extrabold text-violet-600">{grade}</span></div><div className="mt-4 flex items-center gap-3"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: progress }} /></div><span className="text-[10px] text-slate-500">{progress}</span><button className="rounded bg-violet-50 p-1 text-violet-600"><Download className="size-3" /></button></div></div>)}</div></Panel>; }

function Schedule() { const blocks = [{ day: 'Lun 12', hour: '10:00', label: 'Bases de Données', tone: 'bg-emerald-100 text-emerald-700' }, { day: 'Mar 13', hour: '14:00', label: 'Algorithmique', tone: 'bg-orange-100 text-orange-700' }, { day: 'Jeu 15', hour: '08:00', label: 'Algorithmique', tone: 'bg-blue-100 text-blue-700' }, { day: 'Ven 16', hour: '16:00', label: 'Anglais', tone: 'bg-violet-100 text-violet-700' }]; return <Panel title="Emploi du temps"><div className="mt-4 overflow-x-auto"><div className="min-w-[650px]"><div className="grid grid-cols-[70px_repeat(6,1fr)] border-b border-slate-100 text-center text-[11px] font-bold text-slate-500"><span></span>{['Lun 12','Mar 13','Mer 14','Jeu 15','Ven 16','Sam 17'].map(day => <span key={day} className="p-2">{day}</span>)}</div>{['08:00','10:00','12:00','14:00','16:00','18:00'].map(hour => <div key={hour} className="grid grid-cols-[70px_repeat(6,1fr)] border-b border-slate-100"><span className="p-3 text-[10px] text-slate-400">{hour}</span>{['Lun 12','Mar 13','Mer 14','Jeu 15','Ven 16','Sam 17'].map(day => { const block = blocks.find(b => b.day === day && b.hour === hour); return <div key={day} className="min-h-14 border-l border-slate-100 p-1">{block && <div className={`rounded p-1.5 text-[9px] font-bold ${block.tone}`}>{block.label}<br /><span className="font-normal">B204</span></div>}</div>; })}</div>)}</div></div></Panel>; }

function Grades() { return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Metric label="Moyenne générale" value="15,2/20" /><Metric label="Moyenne UE" value="14,8/20" /><Metric label="Classement" value="4/28" /></div><Panel title="Mes notes" action="Semestre 2 (2024/2025)"><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="border-b border-slate-100 text-[10px] text-slate-400"><tr><th className="pb-3">Matière</th><th>CC</th><th>Examen</th><th>Total</th><th>Crédits</th><th>Appréciation</th></tr></thead><tbody>{courseRows.map(([name,,grade], index) => <tr key={name} className="border-b border-slate-100"><td className="py-3 font-bold">{name}</td><td>14,0</td><td>{grade.replace('/20','')}</td><td className="font-bold text-violet-600">{grade}</td><td>6</td><td><span className={`rounded-full px-2 py-1 text-[10px] ${index < 3 ? 'bg-emerald-50 text-emerald-600' : 'bg-orange-50 text-orange-600'}`}>{index < 3 ? 'Bien' : 'Passable'}</span></td></tr>)}</tbody></table></div><button className="mt-4 w-full rounded-lg bg-violet-50 py-2 text-xs font-bold text-violet-600">Voir mon relevé officiel</button></Panel></div>; }

function Documents() { const docs = ['Carte d’étudiant', 'Attestation d’inscription', 'Certificat de scolarité', 'Photo d’identité']; return <div className="space-y-4"><Panel title="Documents personnels" action="Mes demandes"><div className="mt-3 divide-y divide-slate-100">{docs.map((doc, index) => <div key={doc} className="flex items-center gap-3 py-3"><FileText className="size-5 text-emerald-500" /><div className="flex-1"><p className="text-xs font-bold">{doc}</p><p className="mt-1 text-[10px] text-slate-500">Ajouté le {index + 10}/06/2024</p></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-600">Validé</span><button className="rounded p-1 text-violet-600"><Download className="size-4" /></button></div>)}</div></Panel><Panel title="Documents administratifs"><div className="mt-3 flex items-center gap-3 rounded-xl bg-violet-50 p-3"><FileText className="size-5 text-violet-600" /><div className="flex-1"><p className="text-xs font-bold">Relevé de notes S1</p><p className="text-[10px] text-slate-500">Généré le 20/06/2025</p></div><button className="rounded bg-white p-1 text-violet-600"><Download className="size-4" /></button></div></Panel></div>; }

function Messages() { const messages = [['Service Scolarité','Réinscription 2025–2026','Bonjour, la réinscription en ligne est ouverte jusqu’au 30 juin…','10:30'],['Pr. Rakotomalala L.','Devoir Algorithmique','N’oubliez pas de rendre votre devoir avant le 15 juin.','Hier'],['Bibliothèque','Nouveautés – Mai 2025','Découvrez les nouveaux ouvrages disponibles…','06/06'],['Club Robotique','Réunion hebdomadaire','Notre prochaine réunion aura lieu vendredi à 14h.','05/06']]; return <Panel title="Messages" action="✦ Nouveau message"><div className="mt-3 divide-y divide-slate-100">{messages.map(([sender, title, excerpt, date]) => <div key={title} className="flex gap-3 py-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-violet-100 text-xs font-bold text-violet-600">{sender[0]}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="text-xs font-bold">{sender}</p><span className="text-[10px] text-slate-400">{date}</span></div><p className="mt-1 text-xs font-semibold text-slate-700">{title}</p><p className="mt-1 truncate text-[11px] text-slate-500">{excerpt}</p></div></div>)}</div><button className="mt-3 w-full rounded-lg bg-violet-50 py-2 text-xs font-bold text-violet-600">Voir tous les messages</button></Panel>; }

function SettingsView() { return <div className="space-y-4"><Panel title="Informations personnelles"><div className="grid gap-4 md:grid-cols-[1fr_200px]"><div className="divide-y divide-slate-100 rounded-xl border border-slate-100 px-4">{[['Nom complet','Toavina Randriamihaja'],['Email','toavina.r@gmail.com'],['Téléphone','034 12 345 67'],['Date de naissance','12/05/2003'],['Adresse','Antananarivo, Madagascar']].map(([key,value]) => <div key={key} className="grid grid-cols-2 py-3 text-xs"><span className="text-slate-500">{key}</span><span className="font-bold">{value}</span></div>)}</div><div className="rounded-xl bg-slate-50 p-4 text-center"><span className="mx-auto flex size-20 items-center justify-center rounded-full bg-violet-200 text-2xl font-bold text-violet-700">T</span><button className="mt-4 rounded-lg bg-white px-3 py-2 text-xs font-bold text-violet-600 shadow-sm">Changer la photo</button><button className="mt-3 block w-full rounded-lg bg-violet-50 px-3 py-2 text-xs font-bold text-violet-600">Modifier le profil</button></div></div></Panel><Panel title="Informations académiques"><div className="mt-3 grid grid-cols-2 gap-3 text-xs"><Info label="Filière" value="Informatique" /><Info label="Niveau" value="2ᵉ année" /></div></Panel></div>; }

function ComingSoon({ title, icon: Icon }: { title: string; icon: typeof Bell }) { return <Panel title={title}><div className="flex flex-col items-center justify-center py-20 text-center"><span className="flex size-14 items-center justify-center rounded-2xl bg-violet-50 text-violet-600"><Icon className="size-7" /></span><p className="mt-4 text-sm font-bold">Cet espace est prêt à être connecté</p><p className="mt-2 max-w-sm text-xs leading-5 text-slate-500">Le lien fonctionne. Son contenu sera alimenté dès que les données correspondantes seront disponibles.</p><Link href="/dashboard/student" className="mt-5 text-xs font-bold text-violet-600">Retour à l’accueil <ChevronRight className="inline size-3" /></Link></div></Panel>; }

function Panel({ title, action, children, className = '' }: { title: string; action?: string; children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_4px_18px_rgba(68,50,140,0.05)] ${className}`}><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-extrabold">{title}</h2>{action && <button className="text-[11px] font-bold text-violet-600">{action}</button>}</div>{children}</section>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-slate-500">{label}</p><p className="mt-1 text-xs font-extrabold text-slate-800">{value}</p></div>; }
function Timeline({ label, date }: { label: string; date: string }) { return <div><p className="font-bold">{label}</p><p className="mt-1 text-[10px] text-slate-500">{date}</p></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-100 bg-white p-4"><p className="text-[10px] text-slate-500">{label}</p><p className="mt-2 text-xl font-extrabold text-violet-600">{value}</p></div>; }
