import type { ReactNode } from 'react';
import Link from 'next/link';
import { Bell, BookOpen, CheckCircle2, ChevronRight, WalletCards } from 'lucide-react';
import { SchoolNewsFeed } from '@/components/shared/school-news-feed';

type View = 'parcours' | 'news' | 'opportunities' | 'library';

export function StudentPortalView({ view }: { view: View }) {
  const titles: Record<View, string> = { parcours: 'Mon parcours', news: 'Actualités', opportunities: 'Stages & emplois', library: 'Bibliothèque' };
  return <div className="mx-auto max-w-[1180px] text-[#111a4b]"><header className="mb-5 flex items-center justify-between"><div><h1 className="text-xl font-extrabold">{titles[view]}</h1><p className="mt-1 text-xs text-muted-foreground">Espace étudiant · ESPA – 2ᵉ année Informatique</p></div><button className="relative rounded-lg p-2 text-muted-foreground hover:bg-indigo-50 dark:bg-indigo-500/15"><Bell className="size-5" /><span className="absolute right-1 top-1 size-2 rounded-full bg-rose-500" /></button></header>{renderView(view)}</div>;
}

function renderView(view: View) {
  if (view === 'parcours') return <Parcours />;
  if (view === 'news') return <SchoolNewsFeed />;
  return <ComingSoon title={view === 'opportunities' ? 'Stages & emplois' : 'Bibliothèque en ligne'} icon={view === 'opportunities' ? WalletCards : BookOpen} />;
}

function Parcours() {
  const subjects = [['Algorithmique', '6/6', 'Validé'], ['Bases de Données', '4/6', 'En cours'], ['Réseaux & Télécoms', '2/6', 'En cours'], ['Mathématiques', '6/6', 'Validé'], ['Anglais', '0/6', 'Non commencé'], ['Management', '0/6', 'Non commencé']];
  return <div className="grid gap-4 lg:grid-cols-3"><Panel className="lg:col-span-2" title="Progression du programme"><div className="mt-5 flex items-center gap-7 rounded-xl bg-indigo-50/70 p-5"><div className="flex size-28 shrink-0 items-center justify-center rounded-full border-[10px] border-indigo-200 border-t-indigo-600"><div className="text-center"><p className="text-2xl font-extrabold text-indigo-600 dark:text-indigo-300">60%</p><p className="text-[10px] text-muted-foreground">Complété</p></div></div><div className="grid flex-1 grid-cols-2 gap-4 text-xs"><Info label="Crédits validés" value="18/30" /><Info label="Matières validées" value="12/20" /><Info label="Semestre actuel" value="S2 – 2024/2025" /></div></div></Panel><Panel title="Informations"><div className="mt-3 space-y-3 text-xs"><Info label="Filière" value="Informatique" /><Info label="Niveau" value="2ᵉ année" /><Info label="Admission" value="2023" /><Info label="Statut" value="Régulier" /></div></Panel><Panel className="lg:col-span-2" title="Matières du programme"><div className="mt-3 divide-y divide-border">{subjects.map(([subject, credits, state]) => <div key={subject} className="flex items-center gap-3 py-2.5 text-xs"><CheckCircle2 className={`size-4 ${state === 'Validé' ? 'text-emerald-500 dark:text-emerald-300' : 'text-slate-300'}`} /><span className="flex-1 font-semibold">{subject}</span><span className="text-muted-foreground">{credits}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${state === 'Validé' ? 'bg-emerald-50 dark:bg-emerald-500/15 text-emerald-600 dark:text-emerald-300' : state === 'En cours' ? 'bg-blue-50 dark:bg-blue-500/15 text-blue-600 dark:text-blue-300' : 'bg-rose-50 dark:bg-rose-500/15 text-rose-500 dark:text-rose-300'}`}>{state}</span></div>)}</div></Panel><Panel title="Prochains jalons"><div className="mt-3 space-y-5 border-l-2 border-indigo-200 pl-4 text-xs"><Timeline label="Fin du semestre S2" date="30 juin 2025" /><Timeline label="Examens finaux" date="01 – 12 juillet 2025" /><Timeline label="Publication résultats" date="20 juillet 2025" /><Timeline label="Début S3" date="01 septembre 2025" /></div><button className="mt-5 w-full rounded-lg bg-indigo-600 py-2 text-xs font-bold text-white">Télécharger mon relevé</button></Panel></div>;
}

function ComingSoon({ title, icon: Icon }: { title: string; icon: typeof Bell }) { return <Panel title={title}><div className="flex flex-col items-center justify-center py-20 text-center"><span className="flex size-14 items-center justify-center rounded-2xl bg-indigo-50 dark:bg-indigo-500/15 text-indigo-600 dark:text-indigo-300"><Icon className="size-7" /></span><p className="mt-4 text-sm font-bold">Cet espace est prêt à être connecté</p><p className="mt-2 max-w-sm text-xs leading-5 text-muted-foreground">Le lien fonctionne. Son contenu sera alimenté dès que les données correspondantes seront disponibles.</p><Link href="/dashboard/student" className="mt-5 text-xs font-bold text-indigo-600 dark:text-indigo-300">Retour à l’accueil <ChevronRight className="inline size-3" /></Link></div></Panel>; }

function Panel({ title, action, children, className = '' }: { title: string; action?: string; children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-border bg-card p-5 shadow-[0_4px_18px_rgba(68,50,140,0.05)] ${className}`}><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-extrabold">{title}</h2>{action && <button className="text-[11px] font-bold text-indigo-600 dark:text-indigo-300">{action}</button>}</div>{children}</section>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 text-xs font-extrabold text-foreground">{value}</p></div>; }
function Timeline({ label, date }: { label: string; date: string }) { return <div><p className="font-bold">{label}</p><p className="mt-1 text-[10px] text-muted-foreground">{date}</p></div>; }
